spring.application.name=rapchieuphim

# 1. KẾT NỐI DATABASE (Đã thêm tham số cho phép lấy Public Key)
spring.datasource.url=jdbc:mysql://localhost:3306/rapchieuphimdb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=your_password_here
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. CẤU HÌNH JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Để Hibernate tự nhận diện Dialect (Tốt nhất cho Hibernate 7)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# 3. LOGGING
logging.level.org.hibernate.SQL=DEBUG